= Cadastro com Banco de Dados MySQL utilizando Web Service SOAP

Esta aplicação cria um servidor SOAP que fornece um Web Service para
permitir a realização de cadastros em um banco de dados MySQL.

O projeto usa a Java Persistence API (JPA) para Mapeamento Objeto-Relacional (Object Relational Mapping, ORM)
por meio do framework Hibernate 5.

O projeto foi criado e testado no NetBeans 8.2, uma vez que:

- a versão 9 ainda não possui os plugins para desenvolvimento Web pré-instalados;
- o IntelliJ IDEA Community (que é a versão gratuita) não possui suporte a Java EE (para desenvolvimento Web).

== Projetos

=== Aplicação Servidora

O servidor é um projeto Maven >> Web Application.
O código fonte está disponível na pasta link:cadastro-soap-server[cadastro-soap-server]. 
Ele é dividido em 3 pacotes:

- link:cadastro-soap-server/src/main/java/com/manoelcampos/soapserver/model[model]: ver descrição do pacote em link:cadastro-soap-server/src/main/java/com/manoelcampos/soapserver/model/package-info.java[model/package-info.java].
- link:cadastro-soap-server/src/main/java/com/manoelcampos/soapserver/dao[dao]: ver descrição do pacote em link:cadastro-soap-server/src/main/java/com/manoelcampos/soapserver/dao/package-info.java[dao/package-info.java].
- link:cadastro-soap-server/src/main/java/com/manoelcampos/soapserver/ws[ws]: ver descrição do pacote em link:cadastro-soap-server/src/main/java/com/manoelcampos/soapserver/ws/package-info.java[ws/package-info.java].

Dentro de cada pacote há um arquivo package-info.java que contém a documentação JavaDoc
do pacote, apresentando detalhes de como funcionam as classes e interfaces dentro dele.

==== Configurando o acesso ao Banco de Dados

Como o projeto usa Hibernate, temos o arquivo link:cadastro-soap-server/src/main/resources/META-INF/persistence.xml[persistence.xml] com as configurações necessárias. No entanto, para este projeto, as conexões com o banco de dados estão sendo criadas por meio de um DataSource. Com isto, o App Server se encarrega de configurar e criar as conexões, deixando a aplicação totalmente livre de de saber detalhes de conexão (como IP do servidor de banco de dados, usuário, senha, etc).
Usando um DataSource, o App Server permite criar um _pool_ (piscina/tanque) de conexões para o banco de dados. 
Com o _pool_, diversas conexões são abertas. Quando um cliente conectar e precisar ser feito acesso ao banco, uma destas conexões já estabelecidas é fornecida à aplicação. Isto torna o sistema muito rápido e escalável, uma vez que reaproveitando conexões abertas.

Assim, no arquivo `persistence.xml` devemos apenas indicar, dentro da tag `<jta-data-source>`, o nome do DataSource a ser criado no App Server. Como o DataSource normalmente de ser criado pela interface de administração Web do App Server, para evitar que tenhamos que fazer esse processo manualmente, as configurações de fato da conexão para criação do DataSource são definidas no arquivo link:cadastro-soap-server/src/main/webapp/WEB-INF/glassfish-resources.xml[glassfish-resources.xml].
*Assim, é preciso abrir tal arquivo para verificar se os dados como usuário e senha do MySQL estão corretos.*
Quando você cria um _Persistence Unit_ (o arquivo persistence.xml) pelo NetBeans, selecionando a criação de um DataSource, este arquivo `glassfish-resources.xml` é automaticamente criado.

Ao executar a aplicação, este arquivo é automaticamente lido e o DataSource criado no GlassFish.
Observe que o nome do DataSource usado no arquivo `persistence.xml` deve ser o mesmo definido no atributo
`jndi-name` da tag `<jdbc-resource enabled>` dentro do arquvo `glassfish-resources.xml`.
O nome do DataSource deve ser único para todos os projetos instalados no App Server. 
Assim, se você já tiver uma aplicação que usa um determinado nome de DataSource, para este projeto, deverá escolher outro.
Se você estiver executando o projeto em um laboratório de informática onde outros alunos também rodaram o mesmo projeto,
um erro como `Unable to lookup JNDI name [NomeDoDataSource]` pode ocorrer. Neste caso, tente alterar o nome do DataSource nos arquivos xml indicados acima.


=== Aplicação Cliente para consumir os Web Services

O cliente é apenas um projeto Maven >> Java Application.
Ele fornece uma aplicação console para demonstrar como consumir o Web Service de produtos criado no 
projeto servidor apresentado acima. O código do cliente está disponível na pasta link:cadastro-soap-client[cadastro-soap-client]. 

Observe que é preciso executar a aplicação servidora antes de executar o cliente.

== Requisitos para executar a Aplicação Servidora

=== Servidor de Banco de Dados

O MySQL deve estar instalado e executando na máquina local.
O arquivo link:criar-banco.sh[criar-banco.sh] conecta ao MySQL e criar o banco de dados "cadastro_soap",
criando as tabelas e inserindo dados de teste.

Certifique-se de editar o arquivo para fornecer a senha de root do seu servidor MySQL.
O arquivo pode ser executado no terminal com `sh criar-banco.sh`

=== Servidor de Aplicação

O projeto requer um servidor de aplicação (Application Server, comumente chamados de AppServer ou simplesmente AS) instalado e registrado no NetBeans. Ele foi testado com GlassFish 5. Apesar de o NetBeans 8.2 já vir com o Glass Fish 4.2 instalado e configurado, tal versão apresentou apresentou problemas para funcionar com Web Services SOAP e o Hibernate 5. Por esse motivo, foi utilizado o https://javaee.github.io/glassfish/[GlassFish 5 Full Platform] que pode ser baixado diretamente http://download.oracle.com/glassfish/5.0/release/glassfish-5.0.zip[aqui].

Após baixar o GlassFish, basta descompactar o zip em qualquer lugar, como na pasta do seu usuário no sistema operacional.
Como a maioria dos servidores de aplicação, o GlassFish tem um console de administração web.
Para definir/alterar a senha para acesso a tal console (senha que também é necessária para configurar o GlassFish no NetBeans),
abra um terminal na pasta `bin` onde descompactou o GlassFish. Lá execute o comando abaixo. 

[source,bash]
----
./asadmin change-admin-password
----

Digite `admin` na primeira pergunta para indicar o nome do usuário do GlassFish. Na segunda pergunta apenas digite enter para digitar a senha atual. 
Digite a nova senha como `admin` também, assim fica fácil de lembrar que o usuário e a senha são os mesmos. No ambiente de desenvolvimento isto é perfeito, só não podemos definir uma senha assim em um ambiente de produção.

Se necessário, execute o comando acima como root. O comando acima não funciona com as últimas versões do JDK (pelo menos não o JDK 11).

Como nosso projeto usa um banco MySQL, é preciso baixar o driver JDBC que permite que aplicações Java possam se comunicar com o banco. Uma vez que estamos usando Hibernate para acesso ao banco (mapeamento objeto-relacional), nossa aplicação não depende de tal biblioteca. No entanto, o App Server depende dela, pois ele que vai gerenciar as conexões com o banco.

O driver (que nada mais é que um arquivo .jar) deve ser baixado em https://dev.mysql.com/downloads/connector/j/.
Baixe a versão da biblioteca compatível com a versão do servidor MySQL que estiver usando.
Se tiver MySQL Server 5, precisará da versão 5 ou superior do driver JDBC. No link acima, certifique-se de escolher a opção "Platform Independent", que vai disponibilizar um arquivo zip ou tar.gz.

Após baixar o zip, descompacte ele em uma pasta temporária, pois vamos precisar apenas de um arquivo com o nome no formato `mysql-connector-java-VERSAO-bin.jar`. Considerando que você descompactou o GlassFish em uma pasta chamada `glassfish5`, copie tal arquivo jar para
`glassfish5/glassfish/domains/domain1/lib`.

Por fim, precisamos adicionar o GlassFish 5 no NetBeans para conseguirmos executar a aplicação servidora no GlassFish a partir do NetBeans. Para isto, basta ir na aba "Services" do NetBeans e clicar com o botão direito em "Servers", escolhendo "Add Server...", como mostra https://youtu.be/Z87oeoaAxDI[este vídeo].

== Iniciando a Aplicação a partir do NetBeans

Certifique-se de que o caminho onde você colocou o projeto não possui nenhuma pasta que tenha espaços no nome.
Usar espaços em pastas e arquivos é uma péssima prática de programação, pois normalmente espaços causam erros
na execução de programas na linha de comando. Mesmo que você esteja utilizando ferramentas gráficas,
como o IDE NetBeans, tais ferramentas muitas vezes executam pagramas pela linha de comando sem que saibamos.
Neste projeto em específico, o NetBeans usa a ferramenta `wsimport` da plataforma Java para ler o documento WSDL com a descrição do Web Service SOAP e gerar classes Java para fazer acesso a tal serviço. Tal ferramenta não funciona se o caminho do projeto tiver espaços.

Para iniciar o projeto no NetBeans, o ideal é recompilar todos os fontes clicando em `Executar >> Limpar e Construir` (SHIFT+F11). Depois disso, basta executar o projeto clicando no botão "Play" (F6). Se nenhum AppServer estiver configurado, o NetBeans
vai abrir um assistente para que um seja configurado.

Se tudo correr bem, o NetBeans abrirá o navegador no endereço http://localhost:8080/cadastro-soap-server/.
A página index.html incluída possui um link para a página de teste do Web Service.
Tal página também pode ser acessada pelo NetBeans, clicando com o botão
direito em qualquer Web Service disponibilizado na pasta Web Services.

= Aviso

Como indicado na apresentação link:../webservices.pptx[webservices.pptx], SOAP é um protocolo obsoleto.
Os projetos SOAP disponibilizados aqui visam apenas mostrar o básico, caso você
precise manter um sistema que ainda usa tal protocolo.

Ferramentas como o `wsimport` (usada para ler arquivos WSDL e gerar código Java para acesso a um Web Service) nem são mais disponibilizadas nas versões atuais da plataforma Java como a 11.