= Aplicativo de Mensagens Instantâneas usando Protocolo XMPP em Java

Projeto disponibiliza uma aplicação de chat que utiliza o protocolo http://xmpp.org[XMPP].
A rede XMPP possui uma arquitetura cliente/servidor descentralizada para troca de mensagens praticamente em tempo real.

Este é um projeto maven em Java 8 que utiliza a https://github.com/igniterealtime/Smack[biblioteca Smack] para implementar
a aplicação cliente. Tal biblioteca pode inclusive ser utilizada em aplicações Android.
O maven é um gerenciador de dependências que permite indicarmos quais dependências (bibliotecas) nossa aplicação
utilizad. Assim, o maven faz todo o processo de baixar tais bibliotecas pra nós.
Desta forma, não temos que nos preocupar em descobrir o site das bibliotecas, baixar arquivos e adicionar ao nosso projeto.
Isto isso é gerenciado pelo maven. Melhor ainda, o maven guarda as bibliotecas baixadas em um repositório local na sua máquina.
Em Linux, tal diretório pode ser acessado em `~/.m2/repository`. Assim, a pasta da nossa aplicação fica livre de arquivos que podem ser baixados automaticamente.

Todo projeto maven possui um arquivo link:pom.xml[pom.xml] na raiz. Tal arquivo inclui as configurações e dependências utilizadas pelo projeto. O site https://search.maven.org fornece uma interface para busca de bibliotecas para incluir nos seus projetos. No caso deste projeto, a lista de dependências para usar a biblioteca Smack foi obtida https://github.com/igniterealtime/Smack/wiki/Smack-4.3-Readme-and-Upgrade-Guide[no repositório official no GitHub]. Assim, não tive que descobrir eu mesmo quais eram as dependências necessárias.

== Utilizando um servidor XMPP para a aplicação

A aplicação pode utilizar qualquer servidor XMPP. Por exemplo, podemos conectar em servidores gratuitos como https://www.xabber.com, https://jabber.at, https://chinwag.im ou
https://www.jabbim.com. Para isto, basta criar uma conta em algum deles que será possível executar a aplicação para troca de mensagens instantâneas. Uma lista de outros servidores XMPP públicos está disponível no https://xmpp.net/directory.php[xmpp.net]
ou https://list.jabber.at[jabber.at], por exemplo.

Também é possível instalar seus próprios servidores utilizando
projetos como o https://www.igniterealtime.org/projects/openfire/[Openfire], 
https://github.com/jabberd2/jabberd2[JabberD] ou
https://tigase.net/content/tigase-xmpp-server[Tigase].


== Executando a aplicação

Após criar uma conta em um servidor XMPP gratuito ou instalar seu próprio servidor, as credenciais utilizadas no servidor devem ser usadas para logar na aplicação.

Por exemplo, se você criar uma conta em https://www.xabber.com, será fornecido um login. É importante notar que este login não é seu email. Um login XMPP tem o formato de um email, mas não é um endereço de email que você possivelmente informou ao fazer o cadastro.
Considerando que você tenha criado uma conta no site acima com o nome de usuário `manoelcampos`, então seu login será `manoelcampos@xabber.org`. Este é o login que deve usar para logar na aplicação aqui fornecida.
A partir do login, a aplicação descobre qual o domínio ao qual os usuários deste servidor XMPP estão associados.
Neste exemplo, o domínio é `xabber.org`.

Com estes dados, é possível então enviar mensagens por meio da aplicação disponibilizada. Mas para isso, provavelmente é preciso adicionar os contatos com quem deseja conversar. Se você está apenas testando a aplicação e criou várias contas no mesmo servidor, após adicionar uma conta nos contatos da outra, poderá enviar mensagens entre tais contas.

O site xabber.com fornece uma interface web em https://web.xabber.com. Já o jabber.at fornece uma interface em https://jabber.at/chat. Usando tal interface, é possível então adicionar e aceitar contatos. Você pode roda a aplicação disponibiliza aqui, utilizando uma determinada conta de um destes servidores e abrir a interface web acima com outro usuário. Desta forma, conseguirá ver a troca de mensagens entre diferentes usuários. Neste exemplo, como os usuários estão no mesmo servidor, este realiza todo o processo de comunicação.

Se você criar uma conta em outro serviço como o https://www.jabbim.com e acessar https://chat.jabb.im, poderá adicionar um contato do servidor https://jabber.at. Assim, ao executar a aplicação fornecendo as credenciais do seu usuário do jabbim.com e enviar uma mensagem para um usuário do jabber.at, a mensagem chegará até o servidor do jabbim.com, que encaminhará a mesma para o jabber.at.

== Referências

- https://books.google.com.br/books?isbn=0596555598[Livro "XMPP: The Definitive Guide: Building Real-Time Applications with Jabber"]
- https://books.google.com.br/books?isbn=0470633905[Livro "Professional XMPP Programming with JavaScript and jQuery"]
- http://xmpp.org
- http://xmpp.net
- https://en.wikipedia.org/wiki/XMPP
 
