= Cadastro com Banco de Dados MySQL utilizando WebService SOAP

Esta aplicação criar um servidor SOAP que fornece um WebService para
permitir a realização de cadastros em um banco de dados MySQL.

O projeto usa a Java Persistence API (JPA) para Mapeamento Objeto-Relacional (Object Relational Mapping, ORM)
por meio do framework Hibernate 5.

== Executando o Projeto

=== Servidor de Banco de Dados

O MySQL deve estar instalado e executando na máquina local.
O arquivo link:criar-banco.sh[criar-banco.sh] conecta ao MySQL e criar o banco de dados "cadastro_soap" caso ele não exista.
Certifique-se de editar o arquivo para fornecer a senha de root do seu servidor MySQL.
O arquivo pode ser executado no terminal com `sh criar-banco.sh`

=== Servidor de Aplicação

O projeto requer um servidor de aplicação (Application Server, comumente chamados de AppServer ou simplesmente AS) instalado e registrado no NetBeans. Ele foi testado com GlassFish 5. 
Para iniciar o projeto no NetBeans, o ideal é recompilar todos os fontes clicando em Executar >> Limpar e Construir (SHIFT+F11).
Depois disso, basta executar o projeto clicando no botão "Play" (F6). Se nenhum AppServer estiver configurado, o NetBeans
vai abrir um assistente para que um seja configurado.

Se tudo correr bem, o NetBeans abrirá o navegador no endereço http://localhost:8080/cadastro-soap-server/.
