:imagesdir: images

== Introdução

Nas últimas décadas, a computação tem evoluído muito rapidamente. Tal evolução seguida da popularização da informática tem feito a demanda por recursos computacionais crescer de forma acelerada. Até a década de 80, os chamados _mainframes_ (computadores utilizados como *servidores*) eram grandes, caros e dificilmente eram conectados em rede <<SDPP>>. Antes da era das redes de computadores e da Internet, os _mainframes_ funcionavam de forma isolada, sem possibilitar que múltiplos usuários remotamente pudessem utilizar sua capacidade computacional. 

Os _mainframes_ eram utilizados para realizar tarefas que demandavam alto poder de processamento, normalmente processadas em lote (https://www.ibm.com/support/knowledgecenter/zosbasics/com.ibm.zos.zmainframe/zconc_batchproc.htm[batch processing]), como: 

- processamento de folhas de pagamento de empresas;
- processamento de declarações de imposto de renda;
- processamento de imagens;
- computação científica com a realização de cálculos complexos;
- análise estatística de grande volume de dados como no caso de um censo;
- etc.

Processamento em lote é caracterizado pela execução de um conjunto de tarefas (_jobs_), que após iniciadas, são executadas até o fim, sem a intervenção humana. No entanto, este modelo de processamento centralizado e desconectado impedia que o poder computacional de diversos _mainframes_ pudesse ser combinado para permitir a execução de tarefas cada vez maiores e mais complexas. A abordagem de dividir uma tarefa grande em tarefas menores é chamada de _Divide and Conquer_ ("Dividir para Conquistar" ou "Divisão e Conquista") <<PA>>. Tal divisão permite que estas tarefas menores possam ser executadas simultaneamente em múltiplos computadores. Isto aumenta a eficiência, possibilitando que a tarefa original seja finalizada em menos tempo.

Com a popularização das redes de computadores, o advento da Internet e a crescente informatização, computadores começaram a ser inteligados e sistemas centralizados (monoprocessados) evoluíram para *sistemas distribuídos*. Estes são sistemas multiprocessados, que executam simultaneamente em diversos computadores. 

Existem várias definições de sistemas distribuídos, como <<SDPP>>:

[quote, Tanenbaum e Steen 2008]
Um sistema ditribuído é um conjunto de *computadores independentes* que se *apresenta a seus usuários como um sistema único* e coerente.

e <<SDCP>>:
[quote, Coulouris et. al. 2008]
Um sistema distribuído é aquele no qual os componentes localizados em *computadores interligados em rede* se *comunicam* e *coordenam* suas ações apenas passando *mensagens*.

== Características de um Sistema Distribuído

Tais definições de um sistema distribuído permitem que estes sistemas possuam características como:

. compartilhamento de recursos;
. escalabilidade;
. disponibilidade;
. abertura;
. transparência.
