= Web Services

- Integração entre aplicações heterogêneas
- Execução de processamento e/ou acesso a dados no servidor
- Transparente para firewall
- Protocolo SOAP: Simple Object Access Protocol
    - utiliza XML
    - trafega normalmente sobre HTTP
    - padronizado pela W3C

    - permite que um cliente execute funções em um servidor remoto (RPC / RMI = Remote Method Invocation)
    
    - a interface de programação para acesso a tais funções é padronizada por meio de um arquivo WSDL: Web Service Description Language
    
    - com o WSDL, qualquer programa, desenvolvido
      em uma linguagem com suporte, pode consumir
      um web service SOAP (ele é como um catálogo
      de funções, como um javadoc)
    
    - um dos objetivos principais era garantir
      a integração entre aplicações de diferentes
      empresas e desenvolvidas em diferentes linguagens.
    
    - se a assinatura (interface) das funções no WS mudarem,
      o arquivo WSDL é publicado com tais alterações.
      Assim, desenvolvedores de aplicações clientes podem 
      consultar o novo WSDL para permitir que as aplicações
      cliente continuem consumindo o WS.

- Aplicação de acesso a dados: permite que aplicações clientes façam
  acesso a um banco de dados em um servidor, sem precisar conhecer
  as informações de conexão do banco.
  
  O acesso ao banco pode ser feito a partir de qualquer lugar,
  sem preocupações com bloqueio de portas em firewalls.
  Torna a app cliente mais simples, pois ela só precisa enviar
  e receber dados. Não tem que se preocupar com detalhes de BD
  como abertura de conexão, controle de transações, comandos
  SQL, HQL, JPQL ou qualquer outra linguagem de consulta.
  
- Exemplos de aplicações que podem demandar alto processamento,
  cujas rotinas podem ser implementadas em uma aplicação distribuída: 
  * Exemplo do caixeiro viajante usando Simulated Annealing 
  * Image Processing
  * Machine Learning
