= Sistemas Distribuídos
:source-highlighter: highlightjs
:imagesdir: images
:icons: font
:allow-uri-read:
:safe: unsafe
:numbered:
:listing-caption: Listagem
:experimental:
:figure-caption: Figura

ifdef::env-github[]
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

http://about.me/manoelcampos[Prof. Me. Manoel Campos da Silva Filho]

ifdef::env-github[]
IMPORTANT: Acesse o curso online https://manoelcampos.gitbooks.io/sistemas-distribuidos/[neste link].
O acesso ao curso diretamente pelo GitHub não permite a exibição de vídeos nem a navegação facilitada entre capítulos.

O código fonte de projetos utilizando diferentes tecnologias de sistemas distribuídos, para
as mais diversas finalidades, está disponível na pasta link:projects[projects].
endif::[]

== Objetivos

Apresentar o histórico de sistemas distribuídos, necessidades para criação de sistemas distribuídos, suas características, tipos, desafios e tendências. Apresentar tecnologias atuais e implementar sistemas utilizando tais tecnologias.

== Pré-requisitos

Programação Orientada a Objetos em Java.

