= Cadastro com Banco de Dados MySQL utilizando Web Service SOAP

Esta aplicação cria um servidor SOAP que fornece um Web Service para
permitir a realização de cadastros em um banco de dados MySQL.

O projeto usa a Java Persistence API (JPA) para Mapeamento Objeto-Relacional (Object Relational Mapping, ORM)
por meio do framework Hibernate 5.

== Projetos

=== Aplicação Servidora

O código do projeto do servidor está disponível na pasta link:cadastro-soap-server[cadastro-soap-server]. 
Ele é dividido em 3 pacotes:

- link:cadastro-soap-server/src/main/java/com/manoelcampos/soapserver/model[model]: ver descrição do pacote em link:cadastro-soap-server/src/main/java/com/manoelcampos/soapserver/model/package-info.java[model/package-info.java].
- link:cadastro-soap-server/src/main/java/com/manoelcampos/soapserver/dao[dao]: ver descrição do pacote em link:cadastro-soap-server/src/main/java/com/manoelcampos/soapserver/dao/package-info.java[dao/package-info.java].
- link:cadastro-soap-server/src/main/java/com/manoelcampos/soapserver/ws[ws]: ver descrição do pacote em link:cadastro-soap-server/src/main/java/com/manoelcampos/soapserver/ws/package-info.java[ws/package-info.java].

Dentro de cada pacote há um arquivo package-info.java que contém a documentação JavaDoc
do pacote, apresentando detalhes de como funcionam as classes e interfaces dentro dele.

=== Aplicação Cliente para consumir os Web Services

Uma aplicação console está disponível para demonstrar como consumir o Web Service de produtos criado no 
projeto apresentado acima. O código de tal projeto está disponível na pasta link:cadastro-soap-client[cadastro-soap-client]. 

Observe que é preciso executar a aplicação servidora para depois executar o cliente.

== Requisitos para executar a Aplicação Servidora

=== Servidor de Banco de Dados

O MySQL deve estar instalado e executando na máquina local.
O arquivo link:criar-banco.sh[criar-banco.sh] conecta ao MySQL e criar o banco de dados "cadastro_soap" caso ele não exista.
Certifique-se de editar o arquivo para fornecer a senha de root do seu servidor MySQL.
O arquivo pode ser executado no terminal com `sh criar-banco.sh`

=== Servidor de Aplicação

O projeto requer um servidor de aplicação (Application Server, comumente chamados de AppServer ou simplesmente AS) instalado e registrado no NetBeans. Ele foi testado com GlassFish 5. 
Para iniciar o projeto no NetBeans, o ideal é recompilar todos os fontes clicando em Executar >> Limpar e Construir (SHIFT+F11).
Depois disso, basta executar o projeto clicando no botão "Play" (F6). Se nenhum AppServer estiver configurado, o NetBeans
vai abrir um assistente para que um seja configurado.

Se tudo correr bem, o NetBeans abrirá o navegador no endereço http://localhost:8080/cadastro-soap-server/.
A página index.html incluída possui um link para a página de teste do Web Service.
Tal página também pode ser acessada pelo NetBeans, clicando com o botão
direito em qualquer Web Service disponibilizado na pasta Web Services.
