= Microservices

Web Services REST é provavelmente o estilo arquitetural para a construção de aplicações
distribuídas mais utilizado mundialmente para 
integração de aplicações em diferentes plataformas como Web e mobile.
Inúmeros serviços disponibilizados por gigantes da tecnologia como Google, Facebook,
Microsoft, eBay, Twitter e outros seguem tal estilo.

Historicamente, aplicações são desenvolvidas contendo todas as funcionalidades
em um projeto monolítico (um único projeto contendo tudo).
A escalabilidade de tal aplicação é normalmente feita pela duplicação de componentes como 
servidores de aplicação.
Isto para permitir que a mesma aplicação seja executada em diferentes servidores,
possibilitando assim o balanceamento de carga.

Em uma arquitetura de microserviços, tem-se uma diferente forma de desenvolver e escalar
esta mesma aplicação. O desenvolvimento de tal aplicação é dividido em diferentes projetos menores, 
no lugar de um única grande projeto. Com isto, cada um destes sub-projetos representa um microserviço
que pode:

- ser desenvolvido de forma isolada por diferentes equipes, muitas vezes equipes especializadas no negócio que tal sub-projeto engloba;
- funcionar de forma independente.
- ser instalado em servidores diferentes com configurações específicas, adequadas àquele microserviço.
- ter características específicas de demanda, logo, sobrecarga em um microserviço pode não afetar outros microserviços.
- ter a manutenção facilitada pois se um microserviço para, o sistema como um todo não para: apenas partes ficam inoperantes/inacessíveis.
- ser detectados problemas de uma forma muito mais fácil que em um projeto gigante único.
