linux:
	sudo apt-get install expect -y || brew install expect || echo "Não foi possível instalar o comando expect, utilizada pelos scripts de automatização da execução das aplicações para teste de escalabilidade"
