= Modelo Cliente/Servidor

== Cloud 

Usar o provedor de PaaS Heroku para implantar sistemas e fazer balanceamento de carga.
Cada aluno pode criar uma conta sem informar cartão de crédito.
Assim, podemos tentar fazer load balancing entre diferentes contas tendo a mesma app.
A conta de um aluno poderia tem uma app web que usaria um Roud Robin para balancer
a carga entre os diferentes servidores.

Até mesmo um único aluno pode criar vários containers e balancer carga entre eles.
Os containers no Heroku são chamados de https://www.heroku.com/dynos[Dynos].
Existem recursos para https://devcenter.heroku.com/articles/http-routing[Load Balancing].

AWS Educate não obrigatoriamente exige que o estudante tenha um email institucional.
Um professor participante pode convidá-lo. 
Os alunos podem ser convidados para uma AWS Educate Classrooms.
O login no AWS Educate deve ser feito 
pelo botão "Login do AWS Educate", não pelo "Sign in to Console"
em https://aws.amazon.com/education/awseducate/.

== Sockets: a base para comunicação em rede

- Comunicação síncrona e assíncrona
- https://www.javaworld.com/article/2853780/core-java/socket-programming-for-scalable-systems.html
- Java Sync Sockets (ServerSocket)
  e Async Sockets com NIO2 (https://www.baeldung.com/java-nio2-async-socket-channel)

=== Modelo de requisição: blocking, non-blocking, sync, async, multiplexed IO

- https://notes.shichao.io/unp/ch6/
- https://en.wikipedia.org/wiki/Asynchronous_I/O
- https://www.ibm.com/developerworks/library/l-async/

= Modelo Multicamadas

- Middleware: mais complexo, normalmente pesado, faz muitas tarefas
- Broker: mais simples, normalmente uma parte de um middleware que faz uma tarefa bem específica
- Service Discovery

= WebSockets

- https://socket.io

= Peer-to-Peer (P2P)

- P2P. Skype | Spotify - Large Scale, Low Latency, P2P Music-on-Demand Streaming https://www.csc.kth.se/~gkreitz/spotify-p2p10/

= Messaging

- http://mqtt.org Message Queue Telemetry Transport (MQTT) protocol - publish/subscribe (Facebook Messenger)
- MQTT Broker https://mosquitto.org

- Advanced Message Queuing Protocol (AMQP) - https://www.amqp.org 
- RabbitMQ message broker - que suporta AMQP, MQTT, WebSocket e outros protocolos 
    * https://www.rabbitmq.com
    * https://en.wikipedia.org/wiki/RabbitMQ
- ZeroMQ (brokerless) 
    * http://zeromq.org
    * https://github.com/zeromq/jeromq
- Java Message Service (JMS): https://en.wikipedia.org/wiki/Java_Message_Service
- Mobile Devices
    * https://developer.apple.com/documentation/multipeerconnectivity
    * https://developer.android.com/guide/topics/connectivity/wifip2p.html

== Padrão de mensagens e modelo de entrega

- Publish/Subscribe como padrão de mensagens. 
    * https://aws.amazon.com/pub-sub-messaging/
    * https://cloud.google.com/pubsub/docs/overview
- Push/Pull como modelo de entrega

= Application Server (AS)

- Connection Pooling
- Load Balancer

= Web Services

== REST 

- json-b: uma forma mais automática de pegar objetos java e converter para JSON e vice-versa 
        (sem precisar percorrer cada atributo do objeto individualmente)
    * http://json-b.net
    * https://github.com/eclipse-ee4j/yasson (new implementation after moving to Jakarta EE)
    * https://dzone.com/articles/jsonb-java-api-for-json-binding
    * Exemplo: https://javaee.github.io/tutorial/jsonb002.html
- json-p: construir JSON manualmente via Java (adicionando cada chave individualmente. 
          A home page abaixo mostra um exemplo claro)
    * https://javaee.github.io/jsonp/
- json-b vs json-p: www.quora.com/What-is-the-difference-between-Java-API-for-JSON-processing-JSON-P-and-Java-API-for-JSON-Binding-JSON-B-Dont-they-have-an-overlapping-job


- jax-rs:
       Implementado e disponível no GlassFish
            https://github.com/jersey/jersey (reference implementation)
            https://jersey.github.io
       Implementado e disponível no JBoss
            http://resteasy.jboss.org

- resteasy
        Implementando classes proxy automaticamente no cliente para consumir serviços
        (sem precisar escrever ou gerar o código no IDE): o quarkus faz isso
        https://dennis-xlc.gitbooks.io/restful-java-with-jax-rs-2-0-2rd-edition/content/en/part1/chapter16/resteasy_client_proxies.html
        https://dzone.com/articles/jsonb-java-api-for-json-binding
        
== GraphQL

=== Swagger, SwaggerHub, SwaggerUI

- http://blog.caelum.com.br/modelando-apis-rest-com-swagger/
- http://blog.caelum.com.br/documentando-uma-api-jax-rs-com-swagger/

= SOA

= Cloud Computing

= Microservices

- http://microprofile.io (ver free e-book)
- http://microservices.io
- https://blogs.mulesoft.com/dev/microservices-dev/microservices-versus-esb/

= Circuit Breaker

- https://martinfowler.com/bliki/CircuitBreaker.html

= Architecture Patterns (ver livro na minha biblioteca digital)

- http://artofscalability.com
