= Testes de Escalabilidade de Sockets

Projeto Java que realiza testes de escalabilidade nas aplicações
de socket cliente/servidor desenvolvidas, especificamente:

- servidor de chat bloqueante em Java utilizando a classe SocketServer
- servidor não bloqueante em Java utilizando a classe SocketServerChannel
- servidor de chat não bloqueante utilizando WebSocket e Node.js (a ser testado ainda)

O projeto inclui classes com implementações específicas das versões de socket
bloqueantes e não bloqueantes disponíveis na pasta superior.
No entanto, as implementações aqui fornecidas visam apenas testar a escalabilidade
e não possuem muitas funções que seriam necessárias em uma aplicação real, 
como o processamento de fato de mensagens recebidas.
As mensagens recebidas são apenas descartadas.

Os projetos também não possuem o código comentada como nos anteriores.
O objetivo aqui não é explicar o funcionamento de sockets bloqueantes e não bloqueantes,
mas prover um projeto que permita analisar a escalabilidade de tais servidores
de socket com uma grande quantidade de clientes conectados.

Existem duas classes que implementam servidores de chat:

- link:src/main/java/BlockingChatServer.java[BlockingChatServer]
- link:src/main/java/NonBlockingChatServer.java[NonBlockingChatServer]

== Compilando o projeto

Este é um projeto Maven que pode ser compilado em qualquer IDE.
No NetBeans basta clicar no botão "Construir / Build" para isto.
Pelo terminal basta executar `mvn clean install` na pasta raiz.

Usando qualquer uma das opções, será criado um arquivo `scalability-tests-1.0.0.jar` na pasta `target`.

== Executando os Servidores de Chat

Os servidores aceitam conexão em uma determinada porta, e em qualquer IP
que a máquina tiver (como IPs de diferentes interfaces de rede físicas ou virtuais).
Eles podem ser executados diretamente pelo seu IDE.
No NetBeans basta pressionar SHIFT+F6 para executar a classe atual. 

Pode-se ainda utilizar os comandos mostrados abaixo no terminal, a partir da pasta `target`.

`java -cp scalability-tests-1.0.0.jar BlockingChatServer`

ou 

`java -cp scalability-tests-1.0.0.jar NonBlockingChatServer`

Como os dois servidores usam a mesma porta, eles não podem ser executados em simultâneo na mesma máquina.

== Executando os testes de escalabilidade

Ao executar a classe link:src/main/java/AppSocketChatScalability.java[AppSocketChatScalability], são criadas inúmeras conexões com o servidor de chat que estiver em execução. Tal classe pode ser executada diretamente do seu IDE, ou pelo terminal utilizando o comando abaixo dentro da pasta `target`: 

`java -cp scalability-tests-1.0.0.jar AppSocketChatScalability`

Neste caso, ele vai tentar conectar em um servidor de chat local.
Se desejar conectar em um servidor de chat remoto, pode passar o IP ou conjunto de IPs como parâmetros de linha de comando.

O comando abaixo por exemplo, vai iniciar clientes para conectarem em diferentes IPs do servidor.

`java -cp scalability-tests-1.0.0.jar AppSocketChatScalability 10.107.0.80 10.107.0.81`

== Ambiente de Execução

Como a aplicação que realiza os testes de escalabilidade criar uma enorme quantidade de conexões com o servidor de chat,
se o servidor e tal aplicação forem executadas no mesmo computador, você pode receber alguns erros.

1. O número de portas de comunicação que podem ser abertas em um mesmo computador é de 65535, dos quais
algumas são reservadas pelo sistema operacional e outras que por acaso possam já estar sendo usadas por outras
aplicações em execução. Desta forma, você não conseguirá que o seu servidor, executando na mesma máquina onde roda os testes que cria os inúmeros clientes, consiga aceitar um grande número de conexões.
2. Mesmo que você coloque o servidor de chat para executar em uma máquina diferente,
assim ele não vai abrir inúmeras conexões mas sim aceitar várias, a aplicação java pode limitar
o número de conexões pendentes. Desta forma, se a fila de espera para aceitação de conexões
estiver muito grande, novas conexões podem ser bloqueadas.
Isso pode ocorrer se tentarmos criar uma grande quantidade de clientes ao mesmo tempo.
Tais limites são configurados ao criar o socket do servidor em Java, 
mas há limites do sistema operacional também.
3. Mesmo que o limite de conexões pendentes seja aumentado, como cada socket (cliente ou servidor) é como se fosse um arquivo onde dados são gravados, o sistema operacional limita a quantidade de arquivos que podem ser abertos simultaneamente.

Para este último caso, podemos aumentar este limite no servidor usando o comando `ulimit`, como abaixo:

- `ulimit -a` exibe o limite de arquivos que podem ser abertos simultaneamente (o padrão no meu SO é 4864)
- `ulimit -n max` altera o limite de arquivos que podem ser abertos simultaneamente para o valor máximo indicado

No entanto, o valor máximo de arquivos abertos é limitado ao valor máximo definido pelo kernel.
Existem diversas soluções para estes problemas, como apresentado nas referências abaixo.

== Scripts para automatização da execução das aplicações

Se você possui diversas máquinas onde pode testar as aplicações,
existem alguns scripts para auxiliar neste processo.

O link:transfer-server.sh[transfer-server.sh] é utilizado para transferir o pacote jar da aplicação para a máquina onde você pretende executar o servidor de chat. O script envia o pacote jar da aplicação e o link:start-server.sh[start-server.sh] para tal máquina. Em seguida, este último inicia o servidor de chat na máquina remota.

No entanto, para usar o `transfer-server.sh`, é necessário ter o comando `expect` instalado.
Para instalar o mesmo em Linux (Debian, Ubuntu e derivados) ou macOS, apenas execute `make` na raiz desta pasta no terminal.

== Referências

- http://www.lognormal.com/blog/2012/09/27/linux-tcpip-tuning/
- http://www.skybert.net/unix/maximum-number-of-tcp-connections/
- https://mrotaru.wordpress.com/2013/10/10/scaling-to-12-million-concurrent-connections-how-migratorydata-did-it/
- http://www.macfreek.nl/memory/Kernel_Configuration[TCP/IP Kernel Configuration]