= Projeto Final: Sistemas Distribuídos

O objetivo deste projeto é desenvolver 4 sistemas distribuídos que interoperam por meio de
web services REST utilizando a especificação JAX-RS.
Nenhum destes sistemas precisa ter front-end, apenas o back-end com acesso a banco de dados e 
disponibilização dos endpoints REST (as URLs por meio das quais podemos acessar os serviços).

Todos os sistemas que possuem tabelas de cidades e estados devem utilizar os códigos 
do IBGE para permitir que eles funcionem em conjunto. Se em um sistema uma cidade tiver
um código e em outro sistema tiver outro código, obteremos dados errados ao integrar
estes sistemas.

Uma lista de cidades e estados com os códigos do IBGE pode ser obtida no script link:cidades-brasil-ibge.sql[cidades-brasil-ibge.sql]. Tal script é pra MySQL. Se for utilizar outro banco, adapte o script.

= 1. Sistema de Busca de Voos

O sistema deve possuir tabelas para cadastro da companhia aérea, avião,
cidades, estados, pilotos e voos com o respectivo preço.

Para cada avião deve ser indicada a capacidade de passageiros.
Para cada voo deve ser indicada a cidade de origem e destino,
data/hora de partida e chegada, número do voo, preço do bilhete, avião, piloto e companhia
áerea.

Não é preciso implementar classes DAO para cadastro de todas essas tabelas,
mas apenas para aquelas exibidas na lista a seguir.

Devem ser disponibilizados os seguintes endpoints REST:

1. consultar voos por origem e destino
2. consultar voos por origem, destino e data de partida
3. consultar voos por origem, destino, data de partida e faixa de preço
4. cadastrar reserva do voo
5. alterar reserva do voo
6. excluir reserva do voo

= 2. Sistema de Busca de Hotéis

O sistema deve possuir tabelas para cadastro de cidades, estados, bairros e hotéis. 
Deve existir uma tabela para cadastrar os quartos de um hotel, indicando o número do quarto,
andar, total de camas e preço.

Não é preciso implementar classes DAO para cadastro de todas essas tabelas,
mas apenas para aquelas exibidas na lista a seguir.

Devem ser disponibilizados os seguintes endpoints REST:

1. consultar hotéis por cidade
2. consultar hotéis por bairro de uma cidade
3. consultar hotéis por cidade, faixa de preço e total de camas
4. cadastrar reserva de quarto
5. alterar reserva de quarto
6. excluir reserva de quarto

= 3. Sistema de Busca de Veículos de Aluguel

O sistema deve possuir tabelas para cadastro de cidades, estados, locadoras de veículos
e veículos existentes.
O cadastro dos veículos deve incluir a placa, marca, modelo, ano de fabricação e preço,
se tem ar condicionado ou não, tipo de combustível, se é cambio manual ou automático.

Não é preciso implementar classes DAO para cadastro de todas essas tabelas,
mas apenas para aquelas exibidas na lista a seguir.

Devem ser disponibilizados os seguintes endpoints REST:

1. consultar veículo por cidade, modelo e faixa de preço
2. consultar veículo por cidade, faixa de preço, ar condicional e tipo de câmbio 
2. consultar veículo por cidade, faixa de preço, ar condicional, tipo de câmbio e combustível
4. cadastrar reserva de veículo
5. alterar reserva de veículo
6. excluir reserva de veículo

= 4. Sistema de Agência de Viagem

O sistema deve permitir ao usuário fazer a busca de pacotes de viagem que incluam passagem aérea, hotel e/ou carro para alugar.
Ele deve apenas interoperar (integrar) com os outros sistemas.
O mesmo deve possuir então apenas uma interface gráfica para permitir realizar, em uma única tela, a consulta de voos, hotéis e veículos. 

Tal sistema deve fornecer pelo menos 2 formas de consulta a cada um dos sistemas apresentados acima.
O usuário deve poder escolher as buscas que deseja fazer. Ele pode buscar:

1. apenas voos;
2. apenas hotéis; 
3. voos e hotéis;
4. voos, hotéis e veículos;
5. ou qualquer combinação destes 3 tipos de reservas.


