:imagesdir: ../images

== Disponibilidade

Disponibilidade é uma medida que indica o percentual de tempo que espera-se que o sistema esteja em funcionamento <<SDCP>>.
Tal medida é calculada como `tempo de atividade do sistema/(tempo de atividade + tempo de inatividade)` (Ver http://cloudsimplus.org/docs/MScDissertation-RaysaOliveira.pdf[Tabela 2.1 aqui]).
Um sistema distribuído deve fornecer um alto grau de disponibilidade perante falhas <<SDCP>>.
Uma tabela disponível https://en.wikipedia.org/wiki/High_availability#Percentage_calculation[neste link] mostra o tempo de _downtime_ (em que o serviço fica indisponível) de acordo com o grau de disponibilidade. Um sistema com 99% de disponibilidade fica em média indisponível 3.65 dias no ano.

A disponibilidade está diretamente associada ao nível _k_ de tolerância a falhas apresentado anteriormente.
Tais medidas são diretamente proporcionais: quanto mais tolerante a falhas for um sistema, mais tempo disponível ele ficará.
Um sistema com alto grau de tolerância a falhas será altamente disponível e transparente a falhas. 
Com os recursos da computação em nuvem, serviços de monitoramente podem detectar a falha de uma máquina virtual (por exemplo),
e automaticamente iniciar um nova VM, garantindo assim que o nível de tolerância não seja reduzido e que o balanceamento de carga não seja prejudicado com uma redução do número de máquinas.

== Abertura
